<!DOCTYPE html>
<html lang="FR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>connexion</title>
    <?php include_once './include/script.php'; ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <style>
          body {
            background-color: #002395;
            color: #fff;
            font-family: "Arial", sans-serif;
        }
        .login-container {
            margin-top: 150px;
        }
        .card {
            background-color: #fff;
            border: none;
        }
        .card-header {
            background-color: #002395;
            border-bottom: none;
            color: #fff;
        }
        .card-header h4 {
            font-size: 24px;
            letter-spacing: 2px;
            margin-bottom: 0;
        }
        .form-control {
            background-color: #fff;
            border-color: #002395;
            color: #002395;
        }
        .form-control:focus {
            background-color: #fff;
            border-color: #002395;
            color: #002395;
            box-shadow: none;
        }
        .btn-primary {
            background-color: #ed2939;
            border-color: #ed2939;
            letter-spacing: 2px;
            transition: background-color 0.3s ease;
        }
        .btn-primary:hover {
            background-color: #c40007;
            border-color: #c40007;
        }
    </style>
</head>
<body>
    
<?php include_once './include/menu.php'; ?>
<div class="container">
    
</div>

<div class="container">
    <?php if(isset($_GET['inscription']) && $_GET['inscription']== 'ok'){ ?>
        <p class="alert alert-success">merci de votre inscription</p>
   <?php } ?>

        <div class="row justify-content-center">
            <div class="col-md-6 login-container">
                <div class="card">
                    <div class="card-header text-center">
                        <h4>Connexion</h4>
                    </div>
                    <div class="card-body" method="POST">
                        <form  method="POST" action="connexion.php">
                            <div class="form-group" >
                                <label for="email">Adresse email</label>
                                <input type="email" class="form-control" name="email" placeholder="Entrez votre email">
                            </div>
                            <div class="form-group">
                                <label for="password">Mot de passe</label>
                                <input type="password" class="form-control" name="password" placeholder="Entrez votre mot de passe">
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary" value="submit" >Se connecter</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>









    <!-- Inclusion du fichier JavaScript Bootstrap (facultatif) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

</body>
</html>