<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <?php include_once './include/script.php'; ?>
</head>
<body>
<?php include_once './include/menu.php';?>
   <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">titre</th>
      <th scope="col">contenu</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach($articles as $row){ ?>
    <tr>
      <th scope="col"><?php echo $row->id_article;?></th>
      <td> <?php echo $row->titre;?></td>
      <td> <?php echo $row->contenu;?></td>
      </tr>
      <?php }  ?>


   <tr>

        <td><?php echo $randomArticles->id_article; ?></td>
        <td><?php echo $randomArticles->titre;?></td>
        <td><?php echo $randomArticles->contenu;?></td>
        <td><?php echo $randomArticles->image;?></td>
        <td><?php echo $randomArticles->video;?></td>
    </tr>

   


</body>
</html>